
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-11-03T20:05:46+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "379b8713fa79592b7e45ee4c9b8715efa36e525e",
 "version": "1.9.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
